### PR TITLE
Improve relative time

### PR DESCRIPTION
**Pull request by jerone**
-   Github style relative times
  - uses [HTML Web Components extensions to the standard `<time>` element](https://github.com/github/time-elements)
-   Linkify timestamp for issues, releases, comments and events

**Before:**
2015-10-17 16_01_36-github notifications

**After:**
2015-10-17 16_03_10-github notifications

### CODE REVIEW

**Comment by jerone** [comment]
It looks like the test failed not related to this PR...

**Comment by jerone** [comment]
Anyway to restart the tests?

**Comment by jerone** [comment]
Anything I can do to get this merged?

**Comment by bkeepers** [comment]
Hey @jerone, sorry for the radio silence. Thanks for the pull request! It looks great.

I really like the shorthand that is currently used, but I also agree that it should be consistent with GitHub. I want to pull this down and experiment with it a little before merging it.

**Comment by jerone** [comment]
One thing I prefer about GitHub's relative time that's easier to understand, e.g. for "4M" I always have to think is it months or minutes (maybe also because English isn't my native language).

The old way looks visually probably better. Maybe we can do something with styling GitHub's relative times...

**Comment by jerone** [comment]
I'm cleaning up my account and closing stale PR's. Hoping you are still interested in this PR...

**Comment by jerone** [comment]
Closing as stale for half a year now.

**Pull request closed without merging**
